apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - victoria-logs.yaml
  - vlagent.yaml
  - grafana.yaml
